theme = "flatwhite"

[editor]
mouse = false
line-number = "relative"
auto-format = false
idle-timeout = 0

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = [
  "diagnostics", "workspace-diagnostics", "selections",
  "position", "file-encoding", "file-line-ending", "file-type"]

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.whitespace.render]
# space = "all"
# tab = "all"